# Frontend Dockerfile

# Use the official Node.js image
FROM node:18

# Create and set the working directory
WORKDIR /app

# Copy the package.json and install dependencies
COPY package*.json ./
RUN npm install
RUN pwd
RUN ls -la
RUN ls -la node_modules

# Copy the rest of the application files
COPY . .

# Expose the port that the React development server will run on
EXPOSE 3000

# Start the React development server
CMD ["npm", "start"]